function [ThresholdFdataArray] = input_object(n,avgFnoiseArray)
fc                 = 26e6; % Center frequency (Hz)
FrontEndSampleRate = 1e6;     % Samples per second
FrameLength        = 16384;

% Create receiver and spectrum analyzer System objects
hSDRrRx = comm.SDRRTLReceiver(...
   'CenterFrequency', fc, ...
   'EnableTunerAGC',  true, ...
   'SampleRate',      FrontEndSampleRate, ...
   'SamplesPerFrame', FrameLength, ...
   'OutputDataType',  'double');

% hSpectrum = dsp.SpectrumAnalyzer(...
%    'Name',             'Baseband Spectrum',...
%    'Title',            'Baseband Spectrum', ...
%    'SpectrumType',     'Power density',...
%    'FrequencySpan',    'Full', ...
%    'SampleRate',       FrontEndSampleRate, ...
%    'YLimits',          [-80,10],...
%    'SpectralAverages',  50, ...
%    'FrequencySpan',    'Start and stop frequencies', ...
%    'StartFrequency',   -0.5e6, ...
%    'StopFrequency',    0.5e6,...
%    'Position',         figposition([50 30 30 40]));

New_hSpectrum = dsp.ArrayPlot(...
    'YLimits', [-20, 300],...
     'Position', figposition([5 5 80 60]));
 
%% Main Data
% View spectrum.  While the spectrum analyzer is running, you can measure
% peaks, occupied bandwidth, and other properties of the signal.
if ~isempty(sdrinfo(hSDRrRx.RadioAddress))
    for count = 1 : n
       [data, ~] = step(hSDRrRx);  % no 'len' output needed for blocking operation
       data = data - mean(data);  % remove DC component
%        hSpectrum(data);
       FdataArray(:,count) = smooth(abs(fft(data)),4);
       noise_removed = FdataArray(:,count) - avgFnoiseArray;
       ThresholdFdataArray(:,count) = 18*max(noise_removed...
           - 3.5*std(noise_removed),0);
        New_hSpectrum(ThresholdFdataArray(:,count));
    end
    avgFdataArray = mean(ThresholdFdataArray,2);
    New_hSpectrum(avgFdataArray);
else
   warning(message('SDR:sysobjdemos:MainLoop'))
end

% Release all System objects
release(hSDRrRx);
% release(hSpectrum);
release(New_hSpectrum);
end